version: '3'
services:
    audiube:
        build:
            context: .
            args:
                api_key: ${API_KEY}
        container_name: "audiube"
        volumes:
            - ./static/streams:/app/static/streams
        ports:
            - 5001:5001
        depends_on:
            - mongodb
        environment:
            - MONGO_URI=mongodb://audiubedb
        networks:
            - audiubenet
    mongodb:
        image: mongo:3.6.4
        container_name: "mongodb"
        volumes:
          - ./db:/data/db
        ports:
            - 27017:27017
        networks:
            audiubenet:
                aliases:
                    - "audiubedb"
networks:
    audiubenet:
        driver: bridge